name: Feature to Dev Workflow

on:
  pull_request:
    branches:
      - development
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: pulling code
        run : echo "nothing is happening"
  
