name: Feature to Dev Workflow

on:
  pull_request:
    branches:
      - dev*
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: pulling code
        run : echo "nothing is happening"
  
